### PR TITLE
TINKERplate functionality and fixes to python crashing issue

### PR DESCRIPTION
**Pull request by tyler-stowell**

### CODE REVIEW

**Comment by mharsch** [comment]
Closes #3

**Comment by mharsch** [comment]
Closes #2

**Comment by p51d78th** [comment]
Thanks, for implementing support for the TINKERplate, I was about to write something for it to see it was already in progress.

Is there any additional changes required? If so I can help.

**Comment by mharsch** [comment]
We'll get this published today.  Any TINKERplate features you were looking for in particular?  The API here is incomplete, but many of the functions can be implemented in flows or sub-flows.

**Comment by p51d78th** [comment]
Right now just the Digital Outputs and ADC's.

**Comment by p51d78th** [comment]
Thanks for merging that in.  Can you also refresh the Node-Red repo so it can be installed per [this post](https://discourse.nodered.org/t/npm-publish-isnt-updating-flows-nodered-org-solved/1452/14)

**Comment by mharsch** [comment]
Thanks for the tip and the pointer.  Flows page has now refreshed.

**Comment by p51d78th** [comment]
Thanks, everything seems to be working good.

**Pull request merged**
